#!bash
# vim:ff=unix:enc=utf8:ts=3:sw=3:et

# src2pkg-ng - package creation toolkit
# Copyright (C) 2005-2009 Gilbert Ashley
# Copyright (C) 2009 Timothy Goya

# src2pkg-ng is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2 as 
# published by the Free Software Foundation

# src2pkg-ng is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with src2pkg-ng.  If not, see <http://www.gnu.org/licenses/>.

CLEANUP_CMDS=()

add_cleanup_cmd() {
   declare level="$1"
   declare cmd="$2"
   if (( CLEANUP_LEVEL >= level )) ; then
      push_front CLEANUP_CMDS "$cmd"
   fi
   export CLEANUP_CMDS
}

cleanup() {
   if (( ${#CLEANUP_CMDS[@]} )) ; then
      tprintf $"@summary{Cleaning up} - "
      declare cmd=""
      for cmd in "${CLEANUP_CMDS[@]}" ; do
         echo " $cmd"
         $cmd
      done
      tprintf $"@success{Done}\n"
   fi
   unset CLEANUP_CMDS
   if [[ "${1:-""}" ]] ; then
      exit $1
   fi
}

trap "cleanup 1" SIGINT ERR
